dist: xenial   # required for Python >= 3.7
language: python
os:
  - linux
python:
  - "3.6"
  #- "3.7"
sudo: false
install:
  - make install
  - make start
before_script:
  - sleep 15
script:
  - make testall
  - make pep8
