# WiredTiger enables journaling by default; newer MongoDB versions require it.
storage:
  dbPath: ${parts.mongodb['lib-directory']}
net:
  port: ${parts.mongodb['port']}
  bindIp: ${parts.mongodb['bind-ip']}
